name: Release workflow

on:
  push:
    tags:     [ 'v*' ]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Create release file
      run: |
        cd dist
        TAG_NAME=${GITHUB_REF#refs/tags/}
        tar -czf ../dkg-frontend-$TAG_NAME.tar.gz *

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: 'dkg-frontend-*.tar.gz'
        prerelease: ${{ contains(github.ref, '.rc') && 'true' || 'false' }}
